import Head from "next/head";
import React from "react";
import { Box, Typography, Drawer } from "@mui/material";

function Boxs() {
  return (
    <>
      <Head>
        <title>Box</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <div>
        <Box>
          <Typography variant="h3" gutterBottom align="center">
            MUI-BOX 3
          </Typography>
          <Typography variant="h4" gutterBottom align="center">
            MUI-BOX 4
          </Typography>
          <Typography variant="subtitle1" align="center" mt={5}>
            The UMD links use the latest tag to point to the latest version of
            the library. This pointer is unstable and subject to change as we
            release new versions. You should consider pointing to a specific
            version, such as v5.0.0.
          </Typography>
        </Box>
      </div>
    </>
  );
}

export default Boxs;
