import ButtonSpacking from "@/component/Button/ButtonSpacking";
import ItemGrid from "@/component/Paper/ItemGrid";
import { Box, Grid, Paper, styled } from "@mui/material";
import Head from "next/head";
import React, { useState } from "react";

function Grids(props: any) {
  const [valueSpacing, setValueSpacing] = useState(2);

  return (
    <>
      <Head>
        <title>Grid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      {/* EX 1 */}
      <Grid container spacing={2}>
        <Grid item xs={8}>
          <ItemGrid />
        </Grid>
        <Grid item xs={4}>
          <ItemGrid />
        </Grid>

        <Grid item xs={4}>
          <ItemGrid />
        </Grid>
        <Grid item xs={8}>
          <ItemGrid />
        </Grid>

        <Grid item xs={12}>
          <ItemGrid />
        </Grid>

        <Grid item xs={6}>
          <ItemGrid />
        </Grid>
        <Grid item xs={6}>
          <ItemGrid />
        </Grid>
      </Grid>

      <br />
      <br />
      <hr />
      <br />
      <br />

      {/* EX 2 */}
      <Grid container spacing={valueSpacing}>
        <Grid item xs={4}>
          <ItemGrid />
        </Grid>
        <Grid item xs={4}>
          <ItemGrid />
        </Grid>
        <Grid item xs={4}>
          <ItemGrid />
        </Grid>
      </Grid>

      <Box sx={{ textAlign: "center", marginTop: "20px" }}>
        <ButtonSpacking
          handleChangeSpacking={(index: number) => {
            setValueSpacing(index);
          }}
        />
        ;
      </Box>
    </>
  );
}

export default Grids;
