import TourCard from "@/component/Paper/TourCard";
import { Box, Paper } from "@mui/material";
import Head from "next/head";
import React from "react";

function Papers() {
  return (
    <div>
      <Head>
        <title>Paper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <Box>
        <TourCard />
      </Box>
    </div>
  );
}

export default Papers;
